### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main#22]
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main/blob/0aaa6143e1d1a637f501452ff02dffc3f1e7ca08/src/main/java/com/greenfox/dramacsoport/petclinicbackend/config/webtoken/JwtAuthenticationFilter.java#L34

This should work fine, although if someone is looking at this code might not be able to tell at the first glance where the `7` is coming from. Can we eliminate it with a reference maybe to the `Bearer ` prefix somehow?

**Comment by Vozard** [comment]
Done.
