### ISSUE TITLE
Cors Configuration

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main#24]
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main/blob/0aaa6143e1d1a637f501452ff02dffc3f1e7ca08/src/main/java/com/greenfox/dramacsoport/petclinicbackend/config/SecurityConfiguration.java#L56

First of all this works as is.
Although this is not a good practice to hard code configuration in the application. Since you need to re-build and re-distribute the application with every change in the configuration. I definitely would put it in environment variables to avoid this to happen.

Example: 
Usage: 
https://github.com/green-fox-academy/petClinicProject/blob/series/episode-13/petClinicAPI/src/main/java/com/greenfoxacademy/petclinicapi/security/ApplicationSecurity.java

Declaration in the app:
https://github.com/green-fox-academy/petClinicProject/blob/series/episode-13/petClinicAPI/src/main/java/com/greenfoxacademy/petclinicapi/configurations/CorsConfiguration.java

Reading at runtime:

https://github.com/green-fox-academy/petClinicProject/blob/07eb1df1c135436ea7fcd51983e45fdd63a8b794/petClinicAPI/src/main/resources/application.yaml#L22-L23

**Comment by Vozard** [comment]
Done.
