### ISSUE TITLE
Invalid info in Readme to delete

### ISSUE THREAD

**Issue by bsnAndras** [gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main#28]
The information about secret key environment variable setup in Readme is no longer valid.
This functionality is served by a secret key generator method in the JWTService class.

Deleting these lines are recommended.

https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main/blame/0aaa6143e1d1a637f501452ff02dffc3f1e7ca08/README.md#L5-L17C83

**Comment by Vozard** [comment]
Done.
