### ISSUE TITLE
Missing displayName handling

### ISSUE THREAD

**Issue by bsnAndras** [gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main#45]
When registrating the user, the DTO has fields email,username,password, but the AppUser entity has email,displayName,password

Recommended solution: rename username field to displayName in the DTO and on frontend too.
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main/blob/592a7e30f27c0c3b248e26384d46224e2e64a948/src/main/java/com/greenfox/dramacsoport/petclinicbackend/dtos/RegisterRequestDTO.java#L10C5-L12C35

**Comment by AIRewan** [comment]
adjusted in, but this one is introducing more features of chaos - maybe it should be lifted out [feature/userhome-data] https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Backend-main/tree/feature/userhome-data

**Comment by Vozard** [comment]
Feature/userHome_data branch solves the issue

**Comment by agisulyok** [comment]
I close the issue, this will be resolved after merging above branch
